spring.data.mongodb.uri=mongodb+srv://andresinho91320_db_user:1PLUGs45sBMXxR3q@juegoscatalogo.sathudd.mongodb.net/juegosCatalogo?retryWrites=true&w=majority&appName=JuegosCatalogo
spring.data.mongodb.database=juegosCatalogo





# Conexión principal usando la variable que definimos en Railway
spring.data.mongodb.uri=${MONGO_URI}

# Esto asegura que busque la base de datos correcta
spring.data.mongodb.database=${MONGO_DB_NAME}

# ¡IMPORTANTE! Esto ayuda a Spring Boot a saber en qué puerto levantar en Railway
server.port=${PORT:8080}